site_name: Defra architecture
site_url: https://defra.github.io/architecture
theme: 
  name: material
  logo: img/code-white.png
  favicon: img/code-black.png
  palette:
    primary: teal
  font:
    text: 'Arial'
    code: 'Roboto Mono'
repo_url: https://github.com/DEFRA/architecture
remote_branch: gh-pages
nav:
  - Home: index.md
  - Guardrails:
    - Placeholder: guardrails/placeholder.md
